global:
  scrape_interval: 15s
# Scraping Prometheus itself
scrape_configs:
- job_name: 'Prometheus'
  static_configs:
  - targets: ['prometheus-service:9090']
# Scraping Kubernetes State Metrics
- job_name: 'Kube-state-metrics'
  static_configs:
    - targets: ['kube-state-metrics.kube-system.svc:8080']