global:
  scrape_interval: 15s
# Scraping Prometheus itself
scrape_configs:
- job_name: 'Prometheus'
  static_configs:
  - targets: ['prometheus-service:9090']
# Scraping Kubernetes State Metrics
- job_name: 'Kube-state-metrics'
  static_configs:
    - targets: ['kube-state-metrics.kube-system.svc:8080']
# Scraping Orderer Metrics (Replace the Target Hostname and Port according to the environment)
- job_name: 'Orderer'
  static_configs:
    - targets: ['hyperledger:9444']
# Scraping Org1 Peer Metrics (Replace the Target Hostname and Port according to the environment)
- job_name: 'Peer-Org1'
  static_configs:
    - targets: ['hyperledger:9445']
# Scraping Org2 Peer Metrics (Replace the Target Hostname and Port according to the environment)
- job_name: 'Peer-Org2'
  static_configs:
    - targets: ['hyperledger:9446']