{
 "title": "Blockchain Dashboard 1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "peer",
    "label": "Peer",
    "query": "label_values(fabric_version, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Fabric Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "fabric_version{job=\"Orderer\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "go_info{job=\"Orderer\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Blockchain Ledger Height",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "ledger_blockchain_height{job=\"Orderer\"}"
    }
   ]
  },
  {
   "title": "Ledger Transaction Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ledger_transaction_count{job=\"Orderer\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Endorsement Proposals Received",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "targets": [
    { "expr": "endorser_proposals_received", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Endorser Proposal Success",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 4 },
   "targets": [
    { "expr": "endorser_successful_proposals", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CouchDB Processing time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "couchdb_processing_time_count" }
   ]
  },
  {
   "title": "Go Memstat GC CPU Fraction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_gc_cpu_fraction" }
   ]
  },
  {
   "title": "GRPC Server Stream Messages Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_stream_messages_received"
    }
   ]
  },
  {
   "title": "Ledger Transactions over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ledger_transaction_count{job=\"Orderer\"}",
     "legendFormat": "{{transaction_type}}"
    }
   ]
  },
  {
   "title": "Ledger Block Storage Commit Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ledger_blockstorage_commit_time_sum{channel=\"mychannel\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Broadcast Processed Count (MyChannel)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "broadcast_processed_count{channel=\"mychannel\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}