{
 "title": "Blockchain Dashboad 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Blockcutter block fill duration count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "blockcutter_block_fill_duration_count",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Consensus etcdraft cluster size",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "consensus_etcdraft_cluster_size",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Consensus etcdraft committed block number",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "consensus_etcdraft_committed_block_number",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Consensus etcdraft leader changes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "consensus_etcdraft_leader_changes",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Consensus etcdraft data persist duration count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "consensus_etcdraft_data_persist_duration_count",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Consensus etcdraft config proposals received",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "consensus_etcdraft_config_proposals_received",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Ledger Block Height",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ledger_blockchain_height", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Ledger blockstorage commit time count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "ledger_blockstorage_commit_time_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Endorser proposals received",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "targets": [
    { "expr": "endorser_proposals_received", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "ledger_block_processing_time_count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "ledger_block_processing_time_count",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Ledger statedb commit time",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "ledger_statedb_commit_time_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Ledger block processing time sum",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "ledger_block_processing_time_sum",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}