kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
  - name: grafana
    nodePort: 30300
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort